List womens_wear_list = [
  {
    "id": 1,
    "title": "Günlük Elbise",
    "price": 200.0,
    "image": "images/womens_wear_images/gunlukElbise.jpg",
  },
  {
    "id": 2,
    "title": "Günlük Elbise 2",
    "price": 100.0,
    "image": "images/womens_wear_images/gunlukelbise2.jpg",
  },
  {
    "id": 3,
    "title": "Günlük Elbise 3",
    "price": 500.0,
    "image": "images/womens_wear_images/gunlukElbise3.jpg",
  },
  {
    "id": 4,
    "title": "Günlük Elbise 4",
    "price": 300.0,
    "image": "images/category_images/elbise.jpeg",
  },
  {
    "id": 5,
    "title": "Günlük Elbise 5",
    "price": 350.0,
    "image": "images/womens_wear_images/gunlukElbise5.jpg",
  },
  {
    "id": 6,
    "title": "Günlük Elbise 6",
    "price": 400.0,
    "image": "images/womens_wear_images/gunlukElbise6.png",
  },
  {
    "id": 1,
    "title": "Günlük Elbise",
    "price": 200.0,
    "image": "images/womens_wear_images/gunlukElbise.jpg",
  },
  {
    "id": 2,
    "title": "Günlük Elbise 2",
    "price": 100.0,
    "image": "images/womens_wear_images/gunlukelbise2.jpg",
  },
  {
    "id": 3,
    "title": "Günlük Elbise 3",
    "price": 500.0,
    "image": "images/womens_wear_images/gunlukElbise3.jpg",
  },
  {
    "id": 4,
    "title": "Günlük Elbise 4",
    "price": 300.0,
    "image": "images/category_images/elbise.jpeg",
  },
  {
    "id": 5,
    "title": "Günlük Elbise 5",
    "price": 350.0,
    "image": "images/womens_wear_images/gunlukElbise5.jpg",
  },
  {
    "id": 6,
    "title": "Günlük Elbise 6",
    "price": 400.0,
    "image": "images/womens_wear_images/gunlukElbise6.png",
  },
];

List mens_wear_list = [
  {
    "id": 1,
    "title": "Gömlek",
    "price": 200.0,
    "image": "images/mens_wear_images/gomlek1.jpg",
  },
  {
    "id": 2,
    "title": "Gömlek 2",
    "price": 100.0,
    "image": "images/mens_wear_images/gomlek2.jpg",
  },
  {
    "id": 3,
    "title": "Gömlek 3",
    "price": 500.0,
    "image": "images/mens_wear_images/gomlek3.jpg",
  },
  {
    "id": 4,
    "title": "Gömlek 4",
    "price": 300.0,
    "image": "images/mens_wear_images/gomlek4.jpg",
  },
  {
    "id": 5,
    "title": "Gömlek 5",
    "price": 350.0,
    "image": "images/mens_wear_images/gomlek5.jpg",
  },
  {
    "id": 1,
    "title": "Gömlek",
    "price": 200.0,
    "image": "images/mens_wear_images/gomlek1.jpg",
  },
  {
    "id": 2,
    "title": "Gömlek 2",
    "price": 100.0,
    "image": "images/mens_wear_images/gomlek2.jpg",
  },
  {
    "id": 3,
    "title": "Gömlek 3",
    "price": 500.0,
    "image": "images/mens_wear_images/gomlek3.jpg",
  },
  {
    "id": 4,
    "title": "Gömlek 4",
    "price": 300.0,
    "image": "images/mens_wear_images/gomlek4.jpg",
  },
  {
    "id": 5,
    "title": "Gömlek 5",
    "price": 350.0,
    "image": "images/mens_wear_images/gomlek5.jpg",
  },
  {
    "id": 1,
    "title": "Gömlek",
    "price": 200.0,
    "image": "images/mens_wear_images/gomlek1.jpg",
  },
  {
    "id": 2,
    "title": "Gömlek 2",
    "price": 100.0,
    "image": "images/mens_wear_images/gomlek2.jpg",
  },
  {
    "id": 3,
    "title": "Gömlek 3",
    "price": 500.0,
    "image": "images/mens_wear_images/gomlek3.jpg",
  },
  {
    "id": 4,
    "title": "Gömlek 4",
    "price": 300.0,
    "image": "images/mens_wear_images/gomlek4.jpg",
  },
  {
    "id": 5,
    "title": "Gömlek 5",
    "price": 350.0,
    "image": "images/mens_wear_images/gomlek5.jpg",
  },
  {
    "id": 1,
    "title": "Gömlek",
    "price": 200.0,
    "image": "images/mens_wear_images/gomlek1.jpg",
  },
  {
    "id": 2,
    "title": "Gömlek 2",
    "price": 100.0,
    "image": "images/mens_wear_images/gomlek2.jpg",
  },
  {
    "id": 3,
    "title": "Gömlek 3",
    "price": 500.0,
    "image": "images/mens_wear_images/gomlek3.jpg",
  },
  {
    "id": 4,
    "title": "Gömlek 4",
    "price": 300.0,
    "image": "images/mens_wear_images/gomlek4.jpg",
  },
  {
    "id": 5,
    "title": "Gömlek 5",
    "price": 350.0,
    "image": "images/mens_wear_images/gomlek5.jpg",
  },
];